### ISSUE TITLE
Saving category changes fails

### ISSUE THREAD

**Issue by luminuu** [ThemeZee/themezee-blocks#9] opened 2020-10-08 15:52 UTC
On a client project where the plugin is used, I'm unable to save changes to the categories. Ticking on/off the checkboxes and saving has absolutely no effect. However it's possible to change the categories when using the Code Editor and editing the category array directly. There are no JS errors visible in the console. Other settings seem to work fine.

Setup:
WordPress: 5.5.1, single site
ThemeZee Magazine Blocks: 1.1.2
Gutenberg plugin not installed
PHP: 7.4.11

**Comment by Netzberufler** [comment] 2020-10-23 09:19
Thanks for letting me know. I'm still trying to figure out how to solve this, since I did not find much time so far to dive into it.

The issue is that selecting categories does not trigger a change in the state anymore, so the category array is not updated immediately. It is updated once you change any other setting like number of posts, because that triggers a change in settings and refreshes all props, including the categories.

**Comment by Netzberufler** [comment] 2020-11-20 11:53
This should be fixed in version 1.1.3. Sorry it took so long.

Turns out it is not a good idea to directly change React props with Array.push. That leads to all sort of weird side effects. So creating a deep copy of the array first seems to fix all issues. In case you ever use arrays as block attributes :-)

**Closed as completed by Netzberufler** 2020-11-20 11:53 UTC
